### PR TITLE
translate intro

### LINKED ISSUE #5: Translate page "Intro"

### PR DESCRIPTION
**Pull request by gothicenemy**

### CODE REVIEW

**Comment by serrhiy** [comment]
looks scary

**Comment by gothicenemy** [comment]
> looks scary

help me!
what i need 2 do?

**Comment by serrhiy** [comment]
you should nothing to do, i will fix conflicts, but pay more attantion about it. Your previos issue was pretty good

**Comment by gothicenemy** [comment]
> i should nothing to do, i will fix conflicts, but pay more attantion about it. Your previos issue was pretty good

trying to work here for the 1st time so i will pay more attention next time, thx for guide on yt!

**Comment by serrhiy** [comment]
you are welcome. The only man who never makes a mistake is the man who never does anything

**Pull request merged**
